// Generated by https://quicktype.io

export interface TechData {
    courses:      Course[];
    technologies: Technology[];
}

export interface Course {
    _id:        string;
    courseCode: string;
    courseName: string;
}

export interface Technology {
    _id:         string;
    name:        string;
    description: string;
    difficulty:  number;
    courses:     TechnologyCourse[];
}

export interface TechnologyCourse {
    code: string;
    name: string;
}
export interface ContentProps {
    courses: Course[];
    technologies: Technology[];    
}
export interface DeleteProps {
    courses: Course[];
    technologies: Technology[];
    onDelete : VoidFunction;
}
export interface AddProps {
    courses: Course[];
    technologies: Technology[];
    onSubmit : VoidFunction;
}
export interface EditProps {
    courses: Course[];
    technologies: Technology[];
    onEdit : VoidFunction;
}